# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [4]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [3]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [5]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [10]:

vec4 = np.linspace(0,2.7,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]

[[0.  0.3]
 [0.6 0.9]
 [1.2 1.5]
 [1.8 2.1]
 [2.4 2.7]]
[[0.  0.3]
 [0.6 0.9]
 [1.2 1.5]
 [1.8 2.1]
 [2.4 2.7]]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones([3,5])
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)
mat5 = np.identity(3)
print('')
print(mat5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [6]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)
np.dot(mat,vec)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


array([ 8, 41, 44])

In [ ]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

In [ ]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

In [8]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.17449841 0.20866617 0.47016372 0.9472717  0.81695037]
 [0.98943198 0.52235164 0.22737395 0.27775865 0.97776174]
 [0.1603372  0.23909095 0.81640724 0.98258811 0.52183336]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]

[[-1.08453715 -0.23512509  1.48496276  0.53862614 -1.82701497]
 [ 0.82647659 -0.97907354  1.33245302  0.67190827 -1.10497461]
 [ 0.08958679  0.08220298  0.74512525 -1.73781883 -0.56065551]
 [-0.22467716 -0.53036236  0.63314407  1.10149381  1.32469272]
 [ 0.23162549  0.71864273 -0.8249232   0.59165303  0.42193159]
 [ 0.53730824  0.36132004  1.19003476 -0.32839276 -0.75379862]
 [ 1.72381764  0.4874957   0.42547566  3.30444083  0.69487719]
 [-0.4317742   1.18259271  0.89150322 -2.02210961  0.62887256]
 [ 0.04082363 -0.40781267 -0.95143917  0.43819548  1.10442394]
 [-0.31919178 -0.16113854 -0.45503565 -0.97671179 -0.53875049]]


In [ ]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

In [ ]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

In [ ]:
# break here for next video!

In [12]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-2.307993    0.53260463  1.34933654  0.55069813 -0.87660197  0.01962415
  0.86441679 -0.52831756 -0.30783829 -0.07950709 -0.87325283  1.13709424
  0.46566504 -0.41857198  1.95456521 -1.69737856  0.5736775  -0.11827205
 -1.42247371]
0.8644167876674735


In [ ]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

In [ ]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

In [9]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.17449841 0.20866617 0.47016372 0.9472717  0.81695037]
 [0.98943198 0.52235164 0.22737395 0.27775865 0.97776174]
 [0.1603372  0.23909095 0.81640724 0.98258811 0.52183336]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]
0.22737395227467394
0.22737395227467394


In [10]:
print(rand_mat[0:2,1:3])

[[0.20866617 0.47016372]
 [0.52235164 0.22737395]]


In [13]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-2.307993    0.53260463  1.34933654  0.55069813 -0.87660197  0.01962415
  0.86441679 -0.52831756 -0.30783829 -0.07950709 -0.87325283  1.13709424
  0.46566504 -0.41857198  1.95456521 -1.69737856  0.5736775  -0.11827205
 -1.42247371]

[-2.307993    0.53260463  1.34933654  4.          4.          0.01962415
  0.86441679 -0.52831756 -0.30783829 -0.07950709 -0.87325283  1.13709424
  0.46566504 -0.41857198  1.95456521 -1.69737856  0.5736775  -0.11827205
 -1.42247371]

[-2.307993    0.53260463  1.34933654  1.          2.          0.01962415
  0.86441679 -0.52831756 -0.30783829 -0.07950709 -0.87325283  1.13709424
  0.46566504 -0.41857198  1.95456521 -1.69737856  0.5736775  -0.11827205
 -1.42247371]


In [14]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.17449841 0.20866617 0.47016372 0.9472717  0.81695037]
 [0.98943198 0.52235164 0.22737395 0.27775865 0.97776174]
 [0.1603372  0.23909095 0.81640724 0.98258811 0.52183336]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]

[[0.17449841 0.20866617 0.47016372 0.9472717  0.81695037]
 [0.98943198 0.52235164 0.22737395 0.         0.        ]
 [0.1603372  0.23909095 0.81640724 0.         0.        ]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]


In [15]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.17449841 0.20866617 0.47016372]
 [0.98943198 0.52235164 0.22737395]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [16]:
print(rand_mat)

[[3.         3.         3.         0.9472717  0.81695037]
 [3.         3.         3.         0.         0.        ]
 [0.1603372  0.23909095 0.81640724 0.         0.        ]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]


In [17]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.9472717  0.81695037]
 [3.         3.         3.         0.         0.        ]
 [0.1603372  0.23909095 0.81640724 0.         0.        ]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]


In [ ]:
# break here for next video

In [18]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-2.4205353  -1.7397436   0.10071986 -0.68438158 -0.66991341 -0.16525283
 -1.41946252 -0.52520038 -0.03513198 -0.12557472 -1.06620544 -0.98071567
  0.71401428  0.83761188 -1.14851397]
[False False  True False False False False False False False False False
  True  True False]
[0.10071986 0.71401428 0.83761188]


In [19]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-1.08453715 -0.23512509  1.48496276  0.53862614 -1.82701497]
 [ 0.82647659 -0.97907354  1.33245302  0.67190827 -1.10497461]
 [ 0.08958679  0.08220298  0.74512525 -1.73781883 -0.56065551]
 [-0.22467716 -0.53036236  0.63314407  1.10149381  1.32469272]
 [ 0.23162549  0.71864273 -0.8249232   0.59165303  0.42193159]
 [ 0.53730824  0.36132004  1.19003476 -0.32839276 -0.75379862]
 [ 1.72381764  0.4874957   0.42547566  3.30444083  0.69487719]
 [-0.4317742   1.18259271  0.89150322 -2.02210961  0.62887256]
 [ 0.04082363 -0.40781267 -0.95143917  0.43819548  1.10442394]
 [-0.31919178 -0.16113854 -0.45503565 -0.97671179 -0.53875049]]
[1.48496276 0.53862614 0.82647659 1.33245302 0.67190827 0.08958679
 0.08220298 0.74512525 0.63314407 1.10149381 1.32469272 0.23162549
 0.71864273 0.59165303 0.42193159 0.53730824 0.36132004 1.19003476
 1.72381764 0.4874957  0.42547566 3.30444083 0.69487719 1.18259271
 0.89150322 0.62887256 0.04082363 0.43819548 1.10442394]


In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [20]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [21]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [22]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.08453715 -0.23512509  1.48496276  0.53862614 -1.82701497]
 [ 0.82647659 -0.97907354  1.33245302  0.67190827 -1.10497461]
 [ 0.08958679  0.08220298  0.74512525 -1.73781883 -0.56065551]
 [-0.22467716 -0.53036236  0.63314407  1.10149381  1.32469272]
 [ 0.23162549  0.71864273 -0.8249232   0.59165303  0.42193159]
 [ 0.53730824  0.36132004  1.19003476 -0.32839276 -0.75379862]
 [ 1.72381764  0.4874957   0.42547566  3.30444083  0.69487719]
 [-0.4317742   1.18259271  0.89150322 -2.02210961  0.62887256]
 [ 0.04082363 -0.40781267 -0.95143917  0.43819548  1.10442394]
 [-0.31919178 -0.16113854 -0.45503565 -0.97671179 -0.53875049]]



In [23]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.9472717  0.81695037]
 [3.         3.         3.         0.         0.        ]
 [0.1603372  0.23909095 0.81640724 0.         0.        ]
 [0.13129602 0.0741105  0.82022194 0.93947194 0.2203356 ]
 [0.0589452  0.21529044 0.73621013 0.2119624  0.04762744]]

[[-1.08453715 -0.23512509  1.48496276  0.53862614 -1.82701497]
 [ 0.82647659 -0.97907354  1.33245302  0.67190827 -1.10497461]
 [ 0.08958679  0.08220298  0.74512525 -1.73781883 -0.56065551]
 [-0.22467716 -0.53036236  0.63314407  1.10149381  1.32469272]
 [ 0.23162549  0.71864273 -0.8249232   0.59165303  0.42193159]
 [ 0.53730824  0.36132004  1.19003476 -0.32839276 -0.75379862]
 [ 1.72381764  0.4874957   0.42547566  3.30444083  0.69487719]
 [-0.4317742   1.18259271  0.89150322 -2.02210961  0.62887256]
 [ 0.04082363 -0.40781267 -0.95143917  0.43819548  1.10442394]
 [-0.31919178 -0.16113854 -0.45503565 -0.97671179 -0.53875049]]
[[3.         3.         3.         0.9472717  0.81695037]
 [3.         3.    

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)