In [2]:
import numpy as np
import pandas as pd

In [11]:
df1 = pd.DataFrame(np.random.randn(5,5),['r1', 'r2', 'r3', 'r4', 'r5'],['c1', 'c2', 'c3', 'c4', 'c5'])
df1

c1        c2        c3        c4        c5
r1 -1.013327 -0.864978 -2.236516  0.356963  0.686624
r2 -0.105536 -0.033868  0.021143  0.528534 -2.519209
r3  0.874851 -0.962451 -2.119101  2.107285  0.182000
r4 -2.005178  0.364185  0.142178 -0.352215  0.867703
r5 -0.240572 -1.008905 -1.199930 -1.158661 -0.884933

In [53]:
df2 = pd.DataFrame({
    'cars':['Ford', 'BMW', 'Fiat'],
    'color': ['Red', 'White', 'Black'],
    'model': ['Figo', 'i3', 'Spider']
    }, index=[1,2,3])
df2

cars  color   model
1  Ford    Red    Figo
2   BMW  White      i3
3  Fiat  Black  Spider

In [52]:
df2.drop(columns=['cars'], axis=0)

color   model
1    Red    Figo
2  White      i3
3  Black  Spider

In [18]:
series1=df2['color']
series1.unique()

array(['Red', 'White', 'Black'], dtype=object)

In [21]:
series1.value_counts()

White    1
Black    1
Red      1
Name: color, dtype: int64

In [25]:
df2[(df2['cars']!='Ford')  & (df2['model']!='i3')]

cars  color   model
3  Fiat  Black  Spider

In [30]:
print(df1.mean())
print('')
df1.min()

c1   -0.497952
c2   -0.501203
c3   -1.078445
c4    0.296381
c5   -0.333563
dtype: float64



c1   -2.005178
c2   -1.008905
c3   -2.236516
c4   -1.158661
c5   -2.519209
dtype: float64

In [32]:
df1[df1>0]

c1        c2        c3        c4        c5
r1       NaN       NaN       NaN  0.356963  0.686624
r2       NaN       NaN  0.021143  0.528534       NaN
r3  0.874851       NaN       NaN  2.107285  0.182000
r4       NaN  0.364185  0.142178       NaN  0.867703
r5       NaN       NaN       NaN       NaN       NaN

In [37]:
# if some series has multiple of the same value then we can group all the unique entries together
mydict = {
  'customer': ['Customer 1', 'Customer 1', 'Customer2', 'Customer2', 'Customer3', 'Customer3'],   
  'product': [1.1,2.1,3.8,4.2,5.5,6.9],
  'product2': [8.2,9.1,11.1,5.2,44.66, 983]
}

df6 = pd.DataFrame(mydict, index=['Purchase 1', 'Purchase 2', 'Purchase 3', 'Purchase 4', 'Purchase 5', 'Purchase 6'])
df6

customer  product  product2
Purchase 1  Customer 1      1.1      8.20
Purchase 2  Customer 1      2.1      9.10
Purchase 3   Customer2      3.8     11.10
Purchase 4   Customer2      4.2      5.20
Purchase 5   Customer3      5.5     44.66
Purchase 6   Customer3      6.9    983.00

In [41]:
grouped = df6.groupby('customer')
print(grouped)

In [43]:
grouped.describe()

product                                           product2          \
             count mean       std  min   25%  50%   75%  max    count    mean   
customer                                                                        
Customer 1     2.0  1.6  0.707107  1.1  1.35  1.6  1.85  2.1      2.0    8.65   
Customer2      2.0  4.0  0.282843  3.8  3.90  4.0  4.10  4.2      2.0    8.15   
Customer3      2.0  6.2  0.989949  5.5  5.85  6.2  6.55  6.9      2.0  513.83   

                                                                
                   std    min      25%     50%      75%    max  
customer                                                        
Customer 1    0.636396   8.20    8.425    8.65    8.875    9.1  
Customer2     4.171930   5.20    6.675    8.15    9.625   11.1  
Customer3   663.506577  44.66  279.245  513.83  748.415  983.0

In [44]:
grouped.mean()

product  product2
customer                     
Customer 1      1.6      8.65
Customer2       4.0      8.15
Customer3       6.2    513.83

In [45]:
grouped.std()

product    product2
customer                        
Customer 1  0.707107    0.636396
Customer2   0.282843    4.171930
Customer3   0.989949  663.506577

In [56]:
l1 = [1,2,3]
l2 = [4,5,6]
l1 + l2

[1, 2, 3, 4, 5, 6]

In [58]:
l1 = [2.0001, 3.908, 4.56]
sum(l1)

10.4681

In [60]:
l1 = [9, 7, 8, 1, 5]
l1.sort(reverse = True)
l1

[9, 8, 7, 5, 1]

In [62]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

def sum3(a,b,c):
    d=a+b+c
    return sum(d)

sum3(l1,l2,l3)

45

In [64]:
f = lambda x,y,z: x*y/z*z
f(1, 5, 78)

5.0

In [65]:
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [66]:
set = [i for i in range(1,100) if i%2 == 0] 
print(set)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [67]:
sentence = 'great learning is a great platform to learn about data science as it has great faculty and content.'
count = [len(i) for i in sentence.split()]
print(count)

[5, 8, 2, 1, 5, 8, 2, 5, 5, 4, 7, 2, 2, 3, 5, 7, 3, 8]


In [71]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [73]:
np.array([[9,8,7],[6,5,4],[3,2,1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [75]:
np.arange(start = 9, stop = 0, step = -1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [78]:
d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
d1 + 1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [80]:
n6 = np.matrix([[ 1, 4, 9, 121, 144, 169], 
[ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])
np.mean(n6)

131.66666666666666

In [82]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
np.dot(n1,n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [83]:
np.arange(20)[2:7]

array([2, 3, 4, 5, 6])

In [85]:
np.arange(20)[0::9] 

array([ 0,  9, 18])

In [86]:
p = np.arange(20)
p[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [87]:
np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])[::-1]

matrix([[9, 4, 8],
        [1, 5, 4],
        [1, 4, 9]])

In [91]:
mat = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
print(mat[::-1])
print('')
mat.T

[[9 4 8]
 [1 5 4]
 [1 4 9]]



matrix([[1, 1, 9],
        [4, 5, 4],
        [9, 4, 8]])

In [8]:
import numpy as np
demo_arr = np.arange(0,10)
demo_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
demo_arr < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [6]:
demo_arr[demo_arr < 6]

array([0, 1, 2, 3, 4, 5])

In [17]:
demo_matrix = np.array([[13,35,74,48],[23,37,37,38],[73,39,93,39]])
demo_matrix[:,(1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [20]:
test_arr = [10,11.5,12,13.5,14,15]
test_arr[2:3]

[12]

In [21]:
list_l = [[12,34,55],[66,45,77],[45,77,88]]
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [26]:
import pandas as pd
score = [10,15,20,25]
pd.Series(data=score,index=['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [33]:
df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=['A', 'B', 'C', 'D'])
newCol = ["a", "b", "c"]
df['Alphabets']=newCol
df

A  B   C   D Alphabets
0  0  1   2   3         a
1  4  5   6   7         b
2  8  9  10  11         c

In [36]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [38]:
da = np.arange(10,21)
ss = da[0:7]
ss[:] = 101
ss

array([101, 101, 101, 101, 101, 101, 101])

In [40]:
flowers=pd.Series([2,3,5,4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [44]:
s1=pd.Series(['a','b'])
s2=pd.Series(['c','d'])
pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

# MLS Exersice

In [7]:
# Reading datasets by using read_csv from pandas package
ratingsDF = pd.read_csv("./data/ratings.csv")
movieDF = pd.read_csv("./data/movie.csv")
userDF = pd.read_csv("./data/user.csv")


In [11]:
ratingsDF.head(5)

user id  movie id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [13]:
movieDF.tail(5)

movie id                          movie title release date  Action  \
1675      1678                          Mat' i syn      6-Feb-98       0   
1676      1679                           B. Monkey      6-Feb-98       0   
1677      1680                       Sliding Doors      1-Jan-98       0   
1678      1681                        You So Crazy      1-Jan-94       0   
1679      1682  Scream of Stone (Schrei aus Stein)      8-Mar-96       0   

      Adventure  Animation  Childrens  Comedy  Crime  Documentary  ...  \
1675          0          0          0       0      0            0  ...   
1676          0          0          0       0      0            0  ...   
1677          0          0          0       0      0            0  ...   
1678          0          0          0       1      0            0  ...   
1679          0          0          0       0      0            0  ...   

      Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  \
1675        0          0       0        0        0        0       0         0   
1676        0          0       0        0        0        1       0         1   
1677        0          0       0        0        0        1       0         0   
1678        0          0       0        0        0        0       0         0   
1679        0          0       0        0        0        0       0         0   

      War  Western  
1675    0        0  
1676    0        0  
1677    0        0  
1678    0        0  
1679    0        0  

[5 rows x 21 columns]

In [15]:
userDF.head(5)

user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [17]:
ratingsDF.shape

(100000, 4)

In [19]:
userDF.shape

(943, 5)

In [21]:
movieDF.shape

(1680, 21)

In [22]:
ratingsDF.dtypes

user id      int64
movie id     int64
rating       int64
timestamp    int64
dtype: object

In [23]:
userDF.dtypes

user id        int64
age            int64
gender        object
occupation    object
zip code      object
dtype: object

In [25]:
movieDF.dtypes

movie id         int64
movie title     object
release date    object
Action           int64
Adventure        int64
Animation        int64
Childrens        int64
Comedy           int64
Crime            int64
Documentary      int64
Drama            int64
Fantasy          int64
Film-Noir        int64
Horror           int64
Musical          int64
Mystery          int64
Romance          int64
Sci-Fi           int64
Thriller         int64
War              int64
Western          int64
dtype: object

In [26]:
ratingsDF.describe()

user id       movie id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [29]:
userDF.describe()

user id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [55]:
movieDF.describe()

movie id       Action    Adventure    Animation    Childrens  \
count  1680.000000  1680.000000  1680.000000  1680.000000  1680.000000   
mean    841.525595     0.149405     0.080357     0.025000     0.072619   
std     485.609591     0.356593     0.271926     0.156171     0.259587   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%     421.750000     0.000000     0.000000     0.000000     0.000000   
50%     841.500000     0.000000     0.000000     0.000000     0.000000   
75%    1261.250000     0.000000     0.000000     0.000000     0.000000   
max    1682.000000     1.000000     1.000000     1.000000     1.000000   

            Comedy        Crime  Documentary        Drama      Fantasy  \
count  1680.000000  1680.000000  1680.000000  1680.000000  1680.000000   
mean      0.300595     0.064881     0.029762     0.431548     0.013095   
std       0.458653     0.246389     0.169980     0.495440     0.113717   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     0.000000     1.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

         Film-Noir       Horror      Musical      Mystery      Romance  \
count  1680.000000  1680.000000  1680.000000  1680.000000  1680.000000   
mean      0.014286     0.054762     0.033333     0.036310     0.147024   
std       0.118701     0.227583     0.179559     0.187115     0.354235   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

            Sci-Fi     Thriller          War      Western  
count  1680.000000  1680.000000  1680.000000  1680.000000  
mean      0.060119     0.149405     0.042262     0.016071  
std       0.237778     0.356593     0.201246     0.125788  
min       0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000

In [61]:
movieDF.isna()

movie id  movie title  release date  Action  Adventure  Animation  \
0        False        False         False   False      False      False   
1        False        False         False   False      False      False   
2        False        False         False   False      False      False   
3        False        False         False   False      False      False   
4        False        False         False   False      False      False   
...        ...          ...           ...     ...        ...        ...   
1675     False        False         False   False      False      False   
1676     False        False         False   False      False      False   
1677     False        False         False   False      False      False   
1678     False        False         False   False      False      False   
1679     False        False         False   False      False      False   

      Childrens  Comedy  Crime  Documentary  ...  Fantasy  Film-Noir  Horror  \
0         False   False  False        False  ...    False      False   False   
1         False   False  False        False  ...    False      False   False   
2         False   False  False        False  ...    False      False   False   
3         False   False  False        False  ...    False      False   False   
4         False   False  False        False  ...    False      False   False   
...         ...     ...    ...          ...  ...      ...        ...     ...   
1675      False   False  False        False  ...    False      False   False   
1676      False   False  False        False  ...    False      False   False   
1677      False   False  False        False  ...    False      False   False   
1678      False   False  False        False  ...    False      False   False   
1679      False   False  False        False  ...    False      False   False   

      Musical  Mystery  Romance  Sci-Fi  Thriller    War  Western  
0       False    False    False   False     False  False    False  
1       False    False    False   False     False  False    False  
2       False    False    False   False     False  False    False  
3       False    False    False   False     False  False    False  
4       False    False    False   False     False  False    False  
...       ...      ...      ...     ...       ...    ...      ...  
1675    False    False    False   False     False  False    False  
1676    False    False    False   False     False  False    False  
1677    False    False    False   False     False  False    False  
1678    False    False    False   False     False  False    False  
1679    False    False    False   False     False  False    False  

[1680 rows x 21 columns]

In [60]:
movieDF.isna().sum()

movie id        0
movie title     0
release date    0
Action          0
Adventure       0
Animation       0
Childrens       0
Comedy          0
Crime           0
Documentary     0
Drama           0
Fantasy         0
Film-Noir       0
Horror          0
Musical         0
Mystery         0
Romance         0
Sci-Fi          0
Thriller        0
War             0
Western         0
dtype: int64

In [37]:
movieDF.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [38]:
movieDF[[ 'Action',
       'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']].sum()

Action         251
Adventure      135
Animation       42
Childrens      122
Comedy         505
Crime          109
Documentary     50
Drama          725
Fantasy         22
Film-Noir       24
Horror          92
Musical         56
Mystery         61
Romance        247
Sci-Fi         101
Thriller       251
War             71
Western         27
dtype: int64

In [40]:
movieDF.loc[:,'Action':'Western'].sum()

Action         251
Adventure      135
Animation       42
Childrens      122
Comedy         505
Crime          109
Documentary     50
Drama          725
Fantasy         22
Film-Noir       24
Horror          92
Musical         56
Mystery         61
Romance        247
Sci-Fi         101
Thriller       251
War             71
Western         27
dtype: int64

In [41]:
# Sorting the movies across genres
number = movieDF.loc[:,'Action':'Western'].sum()
number.sort_values(ascending = False)

Drama          725
Comedy         505
Action         251
Thriller       251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64

In [45]:
# Find the movies that have more than one genre

new_mov_DF = movieDF[['movie id', 'movie title']].copy()
new_mov_DF['genre count'] = movieDF.loc[:,'Action':'Western'].sum(axis=1)
new_mov_DF

movie id                          movie title  genre count
0            1                           Toy Story             3
1            2                           GoldenEye             3
2            3                          Four Rooms             1
3            4                          Get Shorty             3
4            5                             Copycat             3
...        ...                                  ...          ...
1675      1678                          Mat' i syn             1
1676      1679                           B. Monkey             2
1677      1680                       Sliding Doors             2
1678      1681                        You So Crazy             1
1679      1682  Scream of Stone (Schrei aus Stein)             1

[1680 rows x 3 columns]

In [63]:
# Filtering movies that have more than 1 genre
new_mov_DF[new_mov_DF['genre count'] > 1].reset_index()

index  movie id         movie title  genre count
0        0         1          Toy Story             3
1        1         2          GoldenEye             3
2        3         4         Get Shorty             3
3        4         5            Copycat             3
4        6         7     Twelve Monkeys             2
..     ...       ...                 ...          ...
844   1666      1669  MURDER and murder             3
845   1667      1670            Tainted             2
846   1670      1673             Mirage             2
847   1676      1679          B. Monkey             2
848   1677      1680      Sliding Doors             2

[849 rows x 4 columns]

In [69]:
# Find the top 25 movies according to average ratings such that each movie has number of ratings more than 100
ratingsDF['count'] = ratingsDF.groupby(['movie id'])['rating'].count()
ratingsGr100DF = ratingsDF[ratingsDF['count'] > 100].reset_index(drop = True)
ratingsGr100DF.

user id  movie id  rating  timestamp  count
0        186       302       3  891717742  452.0
1         22       377       1  878887116  131.0
2        166       346       1  886397596  209.0
3        253       465       5  891628467  392.0
4        305       451       3  886324817  219.0
..       ...       ...     ...        ...    ...
329       72       568       4  880037203  101.0
330       83       281       5  880307072  104.0
331        7       623       3  891354217  137.0
332      125       382       1  892836623  148.0
333      293       137       3  888904653  134.0

[334 rows x 5 columns]